version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
install:
- ps: .\build\appveyor-install.ps1
build_script:
- ps: .\build\appveyor-build.ps1
test_script:
- ps: .\build\appveyor-test.ps1
artifacts:
- path: '**\*.nupkg'
  name: Package
- path: '**\*.trx'
  name: TestResults